name: Conda package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    name: "CI setup"

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
        os:
          - "ubuntu-latest"

    runs-on: "${{ matrix.os }}"

    # use bash everywhere
    defaults:
      run:
        shell: "bash -l {0}"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: Install Conda environment with Micromamba
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-name: DeepForest
          environment-file: environment.yml
          extra-specs: "python=${{ matrix.python-version }}"
          cache-env: true
          cache-downloads: true

      - name: Run pytest and style tests
        run: |
          pytest -v
          yapf -d --recursive deepforest/ --style=.style.yapf